### ISSUE TITLE
Keybord shortcuts may need translating

### ISSUE THREAD

**Issue by lentzi90** [overleaf/translations#11]
Any keyboard shortcuts that use "special" characters (anything other than letters basically) may need translating in order to match the keyboard layout of a specific language. For example: I have a keyboard with Swedish layout and if I choose to use the ShareLaTeX in Swedish I can see that the shortcut for commenting out something is `Ctrl + /` when what I actually have to press is `Ctrl+'`.

I think that the "comment out" shortcut is the only affected shortcut in Swedish (not counting any Emacs of Vim shortcuts).

**Comment by das7pad** [comment]
Thank you for the feedback. I do not think it is feasible to provide translations for `'every language' X 'every possible keyboard layout'`.
