### ISSUE TITLE
pt translation with wrong keyword

### ISSUE THREAD

**Issue by GQuirino** [overleaf/translations#17]
`(line 57)    "login_with_service": "Logar com _service_",`<br />
keyword should be with two underscores
`(line 57)    "login_with_service": "Logar com __service__",`<br />

screenshot with wrong keyword
![Screenshot from 2019-10-16 22-02-02](https://user-images.githubusercontent.com/15057257/66969624-b96d8580-f060-11e9-9511-72030eb4d3d1.png)

**Comment by GQuirino** [comment]
I saw that this project is not to be edited by hand.
So how can i help to fix this? and fix some typos like described here #4 ? these typos still is in the code!

**Comment by das7pad** [comment]
Fixed in https://github.com/overleaf/translations/commit/4ba4ba21890dc446920e12fed9d7173d08da1d44
