### ISSUE TITLE
Two spelling mistakes

### ISSUE THREAD

**Issue by danilofreire** [overleaf/translations#4]
Hey there! Congratulations for all your work on ShareLaTeX.

I've spotted two small spelling mistakes in the translations. They are:

```
 (line 101) "no_planned_maintenance": "Não há nenhma manutenção planejada",
```

which should read as

```
 (line 101) "no_planned_maintenance": "Não há nenhuma manutenção planejada",
```

and this one:

```
  (line 524) "merge": "Meclar",
```

which should read as

```
  (line 524) "merge": "Mesclar",
```

Nothing serious, though. Thanks!

**Comment by das7pad** [comment]
Thank you for your contribution. The locales have been updated.
